### ISSUE TITLE
pip install drf-extensions is still picking 0.2.8 instead of 0.3.0

### ISSUE THREAD

**Issue by 5amfung** [chibisov/drf-extensions#116]
I guess pypi hasn't been updated to the latest version.  0.2.8 is still being picked up.

**Comment by auvipy** [comment]
yes not pushed to pypi yet. try the master branch with git clone and report if got any issue.

**Comment by JoshAddington** [comment]
Any ETA on getting 0.3.0 on PyPi?

**Comment by cosmith** [comment]
You can download it with `pip install git+https://github.com/chibisov/drf-extensions@master` if you want to use pip

**Comment by tizot** [comment]
Hi! Do you know when you will push the last version on PyPi ? I have some difficulties to make CircleCI work with the solution given above...
Thank you!

**Comment by auvipy** [comment]
master branch only work with 1.8, work on support 1.9 will be started on next week. but if you beat me to do that first please feel free to send a PR!

**Comment by adamn** [comment]
Any update on this?  Just a PyPI version from the last passing build would be great (b8cc970).  Minor versions could follow.

**Comment by auvipy** [comment]
@adamn I'm working hard for last few days to make this project compatible with django 1.9. everything on master should work. The issue is that the tests are failing for some django gurdains issues and small assertion errors. but nevertheless you could use it. Please give it a try on you project and issue anything get wrong.

**Comment by auvipy** [comment]
3.1 rleased
