### ISSUE TITLE
NestedViewSetMixin suport for saving

### ISSUE THREAD

**Issue by cancan101** [chibisov/drf-extensions#15]
Is looks like using the `NestedViewSetMixin` auto generates the filter code for nested routers, but does nothing for saving.

I would recommend something like the following for a URL like `companies/company_pk/locations/location_pk`:

```
    def pre_save(self, obj):
        obj.location = Location.objects.get(pk=self.kwargs['location_slug'],
                                    company__pk=self.kwargs['company_pk']
                                    )
```

to be auto generated so that a user posting to the above URL can omit those fields which are determined by the URL itself.

**Comment by grjones** [comment]
+1 on reopening and solving this issue.  I'm not sure why this would be closed given the level of uncertainty of the current behavior.  I understand the `m2m` issue is the hard piece, but as it is now most developers are going to assume wrongly that the parent is going to be set in the CRUD operations.

**Comment by dochead** [comment]
Just to echo grjones above, took me quite a while to get here after wondering what I was doing wrong because I assumed the parent would be set automagically.

May I suggest that this be made clear in the docs, it's a fairly pertinent piece of info.

**Comment by neokree** [comment]
Hi! 
Why not simple call the <code>self.get_parents_query_dict()</code> for getting all url values?

**Comment by neokree** [comment]
@chibisov I don't know if there is a way to find the model from a related field, but I suppose yes.
```python
def create(self, request, *args, **kwargs):
		parents_query = self.get_parents_query_dict()
		request_data = {}
		
		# insert normal datas
		for key,value in request.data.items():
			request_data[key] = value
		
		# insert parents datas
		for key,value in parents_query.items():
			request_data[key] = Model.objects.get(pk=value) # instead of 'Model' should be the Foreign key related model object
		
		serializer = self.get_serializer(data=request_data)
		serializer.is_valid(raise_exception=True)
		self.perform_create(serializer)
		headers = self.get_success_headers(serializer.data)
		return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)
```
You should add <code>create</code> and <code>update</code> override in <code>NestedViewSetMixin</code>.

I have copied rest_framework implementation of create then I added related datas from parents_query_dict to a new dict and used it in get_serializer instead the base request.data

**Comment by robert-malai** [comment]
+1 for this feature. I will apply the same approach from @neokree;

About the ideology: I've worked with update-able queries: basically named queries used as views in which one can create new records: properties of the filter condition gets applied to the new record.

In the case of nested routes, because you are using identity based filtering, you are creating views which can be updated, in contrast with nested objects, where the question of creation order or meaning of null values has ambiguous answer. I think that semantically they are different problems.

Like the predecessors, I also see this as part of the viewset rather then the serializer.

Thanks,

**Comment by robert-malai** [comment]
(I will apply the same approach from @neokree;)
I'll take that back; one is interested only in the parent relation only; it might suffice to append all the filters as to the current request date, hope for no name collision and the serializer will filter out unneeded values.
The cleanest approach, because kwargs is unsorted, is the one recommended by https://github.com/chibisov/drf-extensions/issues/15#issuecomment-47745649; other solutions won't be that straightforward: the view and the router aren't related by definition, so in the view you cannot access the router hierarchy to get the parent. You could alter the meta of the ViewSet when you make the router association so that you could inject into the view definition the parent relation, but that's messy ...

**Comment by eliezerchavez** [comment]
Guys, doing as recommended by @chibisov results in python complaining about 'base_name' attribute being None...

Any Ideas, thanks from a newbie

**Comment by lucasdavid** [comment]
@neokree, your solution for create works nice for me, but it has one problem: `parents_query.keys()` need to be fields in the `Serializer` used. However, the html render automatically generates form fields for all serializer's fields => unnecessary form inputs are created.
Did you manage to find a way to "hide" the lookup fields from the html forms and OPTIONS schemas?
