### ISSUE TITLE
Add Support for Django 1.11

### ISSUE THREAD

**Issue by clintonb** [chibisov/drf-extensions#187]
Update Travis/tox to test with Django 1.11. Resolve any compatibility issues.

This would also be a good time to add support for Python 3.6.

**Comment by auvipy** [comment]
lets see if I can make it by this month

**Comment by barseghyanartur** [comment]
Django 1.11 support has already been added in the code (and in tests). Please, make a new PyPI release.

**Comment by barseghyanartur** [comment]
@auvipy:

Wow. Any (realistic) ideas/estimates on when would it be implemented?

**Comment by auvipy** [comment]
contributions are welcome

**Comment by barseghyanartur** [comment]
@auvipy:

With all the respect, that's not what I was asking about.

**Comment by clintonb** [comment]
@barseghyanartur what are you asking about? The functionality is mostly present, but the tests are failing. Django 1.11 should not be officially supported until the tests for Django 1.11 pass. @auvipy and @MightySCollins took the time to contribute a significant portion of the effort about four months ago. No one else has picked up where they left off, so the package doesn't officially support Django 1.11.

The majority of the contributors to this package are volunteers. I'd be happy to review your test fixes and help get Django 1.11 support out the door, if you're willing to volunteer your time and expertise.

**Comment by barseghyanartur** [comment]
@clintonb:

My question was very simple and direct. I asked about realistic estimates on when would it be implemented. If there are no plans to upgrade to 1.11 or no clear road-map, better say so.

**Comment by clintonb** [comment]
Based on the inactivity regarding this issue, there is no defined time for support of Django 1.11.

**Comment by MightySCollins** [comment]
Yep looking though the tests unfortunately it seems Django changed some of the etag stuff this package relies on. Looking at the test fails I assume this package will not work correctly with caching in Django 1.11 but with the fix in #197 stops just using the etags breaking. Because of this we have been using it in production now Django 2.0 for quite some time but not using drf-extensions to handle the caching just adding the etag header.

I have a feeling most of the issues are to do with the `test_with_middleware` which is failing and that it might just be a case of the strings or there methods changing slightly but don't have the time to look into it much more right now.

**Comment by auvipy** [comment]
https://github.com/chibisov/drf-extensions/pull/209 more fixes. plz review and help to detect the remaining failures
