### ISSUE TITLE
Add support for DRF 3.6.x

### ISSUE THREAD

**Issue by jplock** [chibisov/drf-extensions#195]
There seems to be issues with the DRF 3.6.4 documentation and the nested router.

**Comment by auvipy** [comment]
that's a shame. will work on it soon

**Comment by jplock** [comment]
Thanks @auvipy !

**Comment by dhm116** [comment]
Part of the issue seemed to stem from the way DRF stores the paths in a nested `OrderedDict` using https://github.com/encode/django-rest-framework/blob/3.6.4/rest_framework/schemas.py#L111 and https://github.com/encode/django-rest-framework/blob/3.6.4/rest_framework/schemas.py#L341..L347 . I'm not sure if there's really a way for the DRF-extensions to do much to accommodate that type of structure, since they're effectively assigning a `coreapi.document.Link` instance to the value of each endpoint key.

**Comment by auvipy** [comment]
work in progress https://github.com/chibisov/drf-extensions/pull/209

plz review and check the remaining errors and point the fixes if possible
