### ISSUE TITLE
How to invalidate only converned cache keys ?

### ISSUE THREAD

**Issue by inspirassion** [chibisov/drf-extensions#222]
Example in the doc invalidates all cache after any update. Is theire a way to invalidate only concerned objects ?

**Comment by SerhiyRomanov** [comment]
It's because all cache keys is result of md5 functions. For one project purposes, I am working on way to form key as raw string and using Redis 'delete_many'. 
For example, my version will generate cache keys like `json:en:main.models.Country`, `json:de:main.models.Country` and then you will be able to delete all results for lang `en`, for instance.

Would it be interested for community?

**Comment by SerhiyRomanov** [comment]
See my commit https://github.com/SerhiyRomanov/drf-extensions/commit/c8b787a83de8dfdf76d92a10357d7fce6ff877e0
