### ISSUE TITLE
HttpResponse has no 'data' on 0.4.0

### ISSUE THREAD

**Issue by mbaragiola** [chibisov/drf-extensions#237]
Hey guys, just tried updating to 0.4.0 and it broke all my tests.

Whenever I do a GET to a filtered cached list, I run the following test to check wether the amount of objects returned is ok:

```
self.assertEqual(
    response.data['count'],
    3
)
```

But now I get the following error:

`AttributeError: 'HttpResponse' object has no attribute 'data'`

Django is 1.11.15, DRF is 3.8.2 and Python is 3.6 (haven't changed their versions, just `drf-extensions`).

Thanks in advance!

EDIT: Forgot to mention this is a cached list.

**Comment by auvipy** [comment]
@codingjoe could you check as you made the change?

**Comment by codingjoe** [comment]
Hi @mbaragiola that looks like it is related to the caching change it did here:
https://github.com/chibisov/drf-extensions/commit/bdce9e0f4b2112097c5371786da5dac85e861066

I would recommend to disable caching in your test environment. If you want to test the cached behavior, need to be aware the the cached response is a regular Django `HttpResponse` not the special DRF one.

**Comment by codingjoe** [comment]
Maybe that should be documented somewhere... but I don't know which place would fit this kind of specialized note.

**Comment by auvipy** [comment]
you can add a BC breaking note on release note of 0.4.0

**Comment by mbaragiola** [comment]
@auvipy @codingjoe thanks for replying!

I'm curious, what's the reason behind this change? Since this is an extension to DRF and not Django itself.

Testing cache is critical to me, so I'm trying to find a workaround but I can't so far access serialized data on HttpResponse.

**Comment by auvipy** [comment]
@codingjoe I also think since it's an extension of drf, we should be able to do so, since its a breaking change, I think if there isn't any workaround for it, we should revert the change. do you have any drfish solution in mind?

**Comment by codingjoe** [comment]
Sorry I need to call for a bit more caution here. Some like – my company included – may already use the improved cache feature. If you revert it now, that could be considered a breaking change as well ;)

@mbaragiola to give you a bit more context. Caching a DRF response as is pickling the whole object is not a good idea. The DRF response object is too large and can even include whole Querysets.
The change that I introduced only caches the actual HTTP response and forgets everything else.

Form a user perspective this change it totally acceptable and we experienced a >100x improvement on delivery time as well as memory footprint on our caching servers. So this really only breaks your tests, because you assume the response to be a DRF response.

I see only possible solutions here, we document that the cache features will return regular HTTPResponses and make sure it is consistent. You will need to adapt your tests then.

"Breaking" the cache again, by blowing it up seems not reasonable to me. I also don't really see a way to cache the original DRF response in a way that satisfies the main need of a cache: To be fast.

That is of course only my opinion, but I hope it explains my reasoning a bit better.

**Comment by mbaragiola** [comment]
If that's truly the case, then I agree @codingjoe

**Comment by codingjoe** [comment]
@auvipy sure thing! I am working on a patch right now.
Question to @mbaragiola I could add a setting that disables the cache behavior. This could be used in a test suite. Would that help?

**Comment by codingjoe** [comment]
sure thing, see https://github.com/chibisov/drf-extensions/pull/240

**Comment by mbaragiola** [comment]
It totally would. Thanks for your work @codingjoe !
