### ISSUE TITLE
list_route isn't working using the ExtendedSimpleRouter.

### ISSUE THREAD

**Issue by Matt3o12** [chibisov/drf-extensions#30]
When using the ExtendedSimpleRouter, list_route won't route the traffic correctly. Instead of using `/viewSet/methods` it uses `/viewSet/pk/methods`. 

The list_route and detail_route decorators where added in DRF 2.4 to replace the @action and @link decorators. There much more flexible and allow routing requests to list views or detailed views. There are extremely helpful when requesting the current user or a list of all users.  
If anyone knows a workaround until this issue is fixed, I'd highly appreciate it.

**Comment by chibisov** [comment]
Please, don't use [collection level controllers](http://chibisov.github.io/drf-extensions/docs/#collection-level-controllers) and [controller endpoint name](http://chibisov.github.io/drf-extensions/docs/#controller-endpoint-name) with DRF => 2.4. These features are hard to maintain because of new [extra link and actions](http://www.django-rest-framework.org/api-guide/routers/#extra-link-and-actions)

If you want to use nesting facilities you should mixin [NestedRouterMixin](http://chibisov.github.io/drf-extensions/docs/#nested-router-mixin) into your router.

Be careful. `ExtendedDefaultRouter` and `ExtendedSimpleRouter` includes deprecated features and can't be used with DRF > 2.4

If you steel have problems, reopen this issue.

**Comment by magarcia** [comment]
This issue still existing as I say in #91.
