### ISSUE TITLE
Support for DRF 3.0.3 url_path

### ISSUE THREAD

**Issue by maryokhin** [chibisov/drf-extensions#70]
Currently it is not possible to use `drf-extensions` routers with <a href="http://www.django-rest-framework.org/topics/release-notes/">DRF 3.0.3</a> `@detail_route(url_path='xxx')` and `@list_route(url_path='xxx')`, because it passes `url_path` in `initkwargs` to the `viewset` instance through `as_view()` which leads to this stack trace:
```python
  File "/Users/maryokhin/Workspace/backend/api/urls.py", line 99, in <module>
    urlpatterns += router.urls
  File "/Users/maryokhin/.virtualenvs/backend/lib/python3.4/site-packages/rest_framework/routers.py", line 79, in urls
    self._urls = patterns('', *self.get_urls())
  File "/Users/maryokhin/.virtualenvs/backend/lib/python3.4/site-packages/rest_framework/routers.py", line 265, in get_urls
    view = viewset.as_view(mapping, **route.initkwargs)
  File "/Users/maryokhin/.virtualenvs/backend/lib/python3.4/site-packages/rest_framework/viewsets.py", line 65, in as_view
    cls.__name__, key))
TypeError: PostViewSet() received an invalid keyword 'url_path'
```
I'll try to look into this issue more closely, and provide a failing test case.

**Comment by maryokhin** [comment]
The reason it's not passed to the view on the core Router implementation, is because it's <a href="https://github.com/tomchristie/django-rest-framework/blob/fdeef89ba79e617ea22dae68a0b42b3f60d67a4d/rest_framework/routers.py#L180">popped out</a>.
```python
url_path = method_kwargs.pop("url_path", None) or methodname
```

**Comment by chibisov** [comment]
#54

**Comment by chibisov** [comment]
Please, don't use [collection level controllers](http://chibisov.github.io/drf-extensions/docs/#collection-level-controllers) and [controller endpoint name](http://chibisov.github.io/drf-extensions/docs/#controller-endpoint-name) with DRF => 2.4. These features are hard to maintain because of new [extra link and actions](http://www.django-rest-framework.org/api-guide/routers/#extra-link-and-actions)

If you want to use nesting facilities you should mixin [NestedRouterMixin](http://chibisov.github.io/drf-extensions/docs/#nested-router-mixin) into your router.

Be careful. `ExtendedDefaultRouter` and `ExtendedSimpleRouter` includes deprecated features and can't be used with DRF > 2.4

If you steel have problems, reopen this issue.

**Comment by maryokhin** [comment]
But I didn't use them :) The issue was about DRF's `@detail_route` and `@list_route` with it's new `url_path` feature + `drf-extensions` router. Anyway, either me or someone from my team will investigate further and notify if the issue should be reported.

**Comment by chibisov** [comment]
But why you need drf-extensions router, if you don't use it's features?

**Comment by maryokhin** [comment]
I meant that we aren't using `@action` and `@link` contollers, because as you said, they are deprecated. We are using the regular router features to build the nested routes + `@detail_route` and `@list_route`.

**Comment by maryokhin** [comment]
For some reason, I missed this sentence:
> If you want to use nesting facilities you should mixin NestedRouterMixin into your router.

And read it as Nested<b>Viewset</b>Mixin, that where all the confusion came from.

**Comment by AndySun25** [comment]
I have switched to using `NestedRouterMixin` with drf's own `SimpleRouter` and url_path is working somewhat. However now I have run into an additional issue.
As the `url_path` is <a href="https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/routers.py#L174">popped out</a> when used, it is unavailable to every subsequent `get_routes` call.

I will provide a rough example with `UserViewSet` and `PostViewSet`:
`UserViewSet` has a nested `PostViewSet` and `PostViewSet` has a `detail_route` with `url_path`.
If `UserViewSet` is registered first to the router, the nested url `user/{pk}/post/{pk}/{url_path}` will be appended correctly. However upon attempting to register `PostViewSet`the route with `url_path` will no longer be appended correctly since it has already been popped when registering the first view.
